# Generated by Django 3.2.18 on 2024-02-09 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_usermanager_userpis'),
    ]

    operations = [
        migrations.AddField(
            model_name='listlabbadunlockpalletproduction',
            name='maplistfillpallet_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.maplistfillpallet'),
        ),
        migrations.AddField(
            model_name='listlabbadunlockplanproduction',
            name='maplistfillplan_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.maplistfillplan'),
        ),
        migrations.AddField(
            model_name='listlabreturnpalletproduction',
            name='maplistfillpallet_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.maplistfillpallet'),
        ),
        migrations.AddField(
            model_name='listlabreturnplanproduction',
            name='maplistfillplan_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.maplistfillplan'),
        ),
    ]
