# Generated by Django 3.2.18 on 2024-02-09 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0003_auto_20240209_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='type_warehouse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='map_management',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.warehouse'),
        ),
    ]
