# Generated by Django 3.2.18 on 2024-02-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0004_auto_20240209_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='map_management',
            name='action_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='map_management',
            name='damaged',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
