# Generated by Django 3.2.18 on 2024-02-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0005_auto_20240209_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSaver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
