# Generated by Django 3.2.18 on 2024-02-14 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0006_datasaver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataSaver',
            new_name='ParameterSave',
        ),
    ]
