# Generated by Django 4.2.5 on 2024-02-21 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0008_auto_20240220_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiger_GoodsIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmainfromwms', models.CharField(db_collation='Thai_CI_AS', max_length=50)),
                ('usermachine', models.CharField(db_collation='Thai_CI_AS', max_length=50)),
                ('machine', models.CharField(db_collation='Thai_CI_AS', max_length=3)),
                ('gdate', models.DateField()),
                ('shift', models.CharField(db_collation='Thai_CI_AS', max_length=1)),
                ('matno', models.CharField(db_collation='Thai_CI_AS', max_length=50)),
                ('matname', models.CharField(db_collation='Thai_CI_AS', max_length=100)),
                ('qty', models.IntegerField()),
                ('pallet', models.CharField(db_collation='Thai_CI_AS', max_length=10)),
                ('ton', models.DecimalField(decimal_places=2, max_digits=18)),
                ('urinsert', models.IntegerField()),
                ('blockinsert', models.IntegerField()),
                ('approver', models.CharField(db_collation='Thai_CI_AS', max_length=50)),
                ('datetimewmssend', models.DateTimeField()),
                ('tigerpart', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=50, null=True)),
                ('datesapgi', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=50, null=True)),
                ('timesapgi', models.TimeField(blank=True, null=True)),
                ('matdocgi', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tiger_goodsissue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FGPlanningStockTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.CharField(blank=True, max_length=100, null=True)),
                ('zca_on', models.CharField(blank=True, max_length=100, null=True)),
                ('name_th', models.CharField(blank=True, max_length=400, null=True)),
                ('name_en', models.CharField(blank=True, max_length=400, null=True)),
                ('location_1_select_1', models.CharField(blank=True, max_length=300, null=True)),
                ('location_1_select_2', models.CharField(blank=True, max_length=300, null=True)),
                ('location_1_select_3', models.CharField(blank=True, max_length=300, null=True)),
                ('location_1_info', models.CharField(blank=True, max_length=600, null=True)),
                ('location_2_select_1', models.CharField(blank=True, max_length=300, null=True)),
                ('location_2_select_2', models.CharField(blank=True, max_length=300, null=True)),
                ('location_2_select_3', models.CharField(blank=True, max_length=300, null=True)),
                ('location_2_info', models.CharField(blank=True, max_length=600, null=True)),
                ('location_3_select_1', models.CharField(blank=True, max_length=300, null=True)),
                ('location_3_select_2', models.CharField(blank=True, max_length=300, null=True)),
                ('location_3_select_3', models.CharField(blank=True, max_length=300, null=True)),
                ('location_3_info', models.CharField(blank=True, max_length=600, null=True)),
                ('location_4_select_1', models.CharField(blank=True, max_length=300, null=True)),
                ('location_4_select_2', models.CharField(blank=True, max_length=300, null=True)),
                ('location_4_select_3', models.CharField(blank=True, max_length=300, null=True)),
                ('location_4_info', models.CharField(blank=True, max_length=600, null=True)),
                ('location_5_select_1', models.CharField(blank=True, max_length=300, null=True)),
                ('location_5_select_2', models.CharField(blank=True, max_length=300, null=True)),
                ('location_5_select_3', models.CharField(blank=True, max_length=300, null=True)),
                ('location_5_info', models.CharField(blank=True, max_length=600, null=True)),
                ('listticketplan_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.listticketplanproduction')),
                ('plan_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.planproduction')),
            ],
        ),
        migrations.DeleteModel(
            name='TigerGoodsIssue',
        ),
    ]
