# Generated by Django 4.1.4 on 2024-02-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0009_tiger_goodsissue_fgplanningstockticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_WIPBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, max_length=100, null=True)),
                ('zca_on', models.CharField(blank=True, max_length=100, null=True)),
                ('name_th', models.CharField(blank=True, max_length=100, null=True)),
                ('priceperunit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Info_WIPBalance',
                'managed': False,
            },
        ),
    ]
