# Generated by Django 4.1.4 on 2024-02-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0010_info_wipbalance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info_wipbalance',
            options={'managed': True},
        ),
    ]
