# Generated by Django 4.1.4 on 2024-03-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0011_alter_info_wipbalance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info_wipbalance',
            options={'managed': False},
        ),
    ]
