# Generated by Django 4.2.5 on 2024-03-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0012_alter_info_wipbalance_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_MCCostcenter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine', models.CharField(blank=True, max_length=100, null=True)),
                ('costcenter_machine', models.CharField(blank=True, max_length=100, null=True)),
                ('costcenter_cutlab', models.CharField(blank=True, max_length=100, null=True)),
                ('costcenter_cutbadafter', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Info_MCCostcenter',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='info_wipbalance',
            options={'managed': True},
        ),
    ]
